kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    username:
      from_secret: ghcr_username
    password: 
      from_secret: ghcr_password
    repo: ghcr.io/${DRONE_REPO,,}
    platform: linux/arm64
    auto_tag: true
